### ISSUE TITLE
Material-UI with CSS in JS, is it good? 

### ISSUE THREAD

**Issue by gmoura** [Laboratoria/ui#48]
Hi guys, 

By default Material-UI use [CSS in JS](https://material-ui.com/customization/css-in-js/#material-ui-39-s-styling-solution), I would like to know if you are comfortable to use CSS in JS in this project.

Gracias

**Comment by rafaelbcerri** [comment]
In the beginning I thought it was a little strange writing `css` in `js` because I was used to create reusable classes for all components, but now that I changed my mindset to write `css` in a component based approach, it is making more sense to write `css` in `js`

In conclusion I'm comfortable using CSS in JS in this project 😃

**Comment by AnaSalazar** [comment]
It is already very common for me to write it that way, I feel comfortable with that.
